services:
  - type: web
    name: procure-to-pay-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "uv run gunicorn core.wsgi:application"
    plan: starter
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: procure-to-pay-db
          property: connectionString

databases:
  - name: procure-to-pay-db
    databaseName: procuretopay
    plan: starter