services:
  # Web Service
  - type: web
    name: procure-to-pay
    env: python
    buildCommand: "./build.sh"
    startCommand: "uv run gunicorn core.wsgi:application"
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: procure-to-pay-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: procure-to-pay.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.5

  # Database
  - type: pserv
    name: procure-to-pay-db
    env: postgresql
    plan: starter
    ipAllowList: []